language: node_js
dist: bionic
node_js:
  - "10"
cache:
  yarn: true

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - master
    - release

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install codecov -g
  - openssl aes-256-cbc -K $encrypted_498d4c4e8b8a_key -iv $encrypted_498d4c4e8b8a_iv -in git_deploy_key.enc -out /tmp/git_deploy_key -d
  - chmod 600 /tmp/git_deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/git_deploy_key

jobs:
  include:
    - name: "Test"
      script: |
        set -ex
        yarn pre-test
        yarn build-tests
        yarn test-rendering-tests --headless-chrome
        yarn check-platform-update-reference-data
        yarn push-reference-rendering-tests
        git status # just in case test-npm-packages leaves some garbage
    - name: "Build & Deploy"
      script: |
        set -ex
        cross-env NODE_ENV=production yarn run build
        yarn run typedoc
      before_deploy: ./scripts/prepare_doc_deploy.sh
      deploy:
                - provider: script
                  script: ./scripts/publish-packages.sh
                  skip_cleanup: true
                  on:
                    branch: release
        - provider: pages
          skip_cleanup: true
          committer-from-gh: true
          keep-history: false
          local-dir: dist/gh_deploy
          github-token: $GITHUB_TOKEN
          on:
            branch: release
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: "harp.gl"
          skip_cleanup: true
          local_dir: dist/s3_deploy
          upload-dir: docs
          region: us-east-1
          acl: public_read
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^master|release$

after_success:
  - codecov -f coverage/*.json
